server:
  port: 8085

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.99.100:5432/order_module
    username: postgres
    password: postgres

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update


  rabbitmq:
    host: 192.168.99.100
    username: root
    password: root
    port: 5672