version: '3'
services:
  postgres:
    image: 'postgres:10'
    container_name: 'java-postgres'
    environment:
      - 'POSTGRES_USER=postgres'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_DB=test'
     ## - 'PGDATA=/var/lib/postgresql/data'
      - 'POSTGRES_INITDB_ARGS= --encoding=UTF-8 --lc-collate=C --lc-ctype=C'

    volumes:
      - pgdata:/var/lib/postgresql/data
      ##- ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - '192.168.99.100:5432:5432'
    expose:
      - "5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 4G

  pgadmin:
    image: dpage/pgadmin4:5.7
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: kotov.svyat@mail.ru
      PGADMIN_DEFAULT_PASSWORD: "postgres"
      PGADMIN_CONFIG_SERVER_MODE: "False"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    ports:
      - "192.168.99.100:5050:80"
    restart: "unless-stopped"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G
    networks:
      - postgres


networks:
  postgres:
    driver: bridge

volumes:
  pgdata: