version: '3'

services:
  shop-module:
    image: svyatoslavkotov/e-shop-micro_order-module:v1.2
    container_name: 'e-shop-micro_order-module'
    env_file:
      - .env
    environment:
      SERVER_PORT: ${SERVER_PORT}

      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}

      SPRING_RABBITMQ_HOST: ${SPRING_RABBITMQ_HOST}
      SPRING_RABBITMQ_PORT: ${SPRING_RABBITMQ_PORT}
      SPRING_RABBITMQ_USERNAME: ${SPRING_RABBITMQ_USERNAME}
      SPRING_RABBITMQ_PASSWORD: ${SPRING_RABBITMQ_PASSWORD}
    restart: always

    ports:
      - '90.156.225.74:${SERVER_PORT}:${SERVER_PORT}'
