version: '3'

services:
  rabbitmq:
    image: rabbitmq:3.11.0-management
    container_name: rabbitMq
    restart: unless-stopped
    environment:
      - 'RABBITMQ_USER= rabbitmq'
      - 'RABBITMQ_PASSWORD=rabbitmq'
      - 'RABBITMQ_HOSTNAME=rabbitmq'
      - 'RABBITMQ_DEFAULT_USER=root'
      - 'RABBITMQ_DEFAULT_PASS=root'
      - 'mountPath=/var/lib/rabbitmq/'
      - 'mountPath=/var/log/rabbitmq/'

    ports:
      - '192.168.99.100:5672:5672'
      - '192.168.99.100:15672:15672'
    volumes:
      - $HOME/docker/volumes/rabbitmq/shopCloud:/var/lib/rabbitmq
      - $HOME/docker/volumes/rabbitmq/logs/shopClouds:/var/log/rabbitmq/logs

volumes:
  rabbitMqData:
  rabbitMqLogs:
