version: '3'

services:
  certbot:
    image: certbot/certbot

    container_name: certbot
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    command: certonly --webroot --webroot-path=/var/www/html --email kotov.svyat@mail.ru --agree-tos --no-eff-email --staging -d e-kotovsvyatoslav.ru